language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
install: composer install --dev
script:
    - phpunit test/ --coverage-clover clover.xml
after_script: php vendor/bin/coveralls -v
